export enum EClassStatus {
  DRAFT = "DRAFT",
  OPEN_FOR_REGISTRATION = "OPEN_FOR_REGISTRATION",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
}

export enum ERegisteredClassStatus {
  COMPLETED = "COMPLETED",
  ENROLLED = "ENROLLED",
  DROPPED = "DROPPED",
}
