import type { TMajor, TSubject } from "@/types";

export const mockMajors: TMajor[] = [
  {
    id: 1,
    majorCode: "CNTT",
    majorName: "Công nghệ thông tin",
    description: "Công nghệ thông tin",
    createdAt: "2024-01-15T08:00:00Z",
  },
  {
    id: 2,
    majorCode: "KHMT",
    majorName: "Khoa học máy tính",
    description: "Khoa học máy tính",
    createdAt: "2024-01-16T09:00:00Z",
  },
  {
    id: 3,
    majorCode: "KTPM",
    majorName: "Kỹ thuật phần mềm",
    description: "Kỹ thuật phần mềm",
    createdAt: "2024-01-17T10:00:00Z",
  },
  {
    id: 4,
    majorCode: "ATTT",
    majorName: "An toàn thông tin",
    description: "An toàn thông tin",
    createdAt: "2024-01-18T11:00:00Z",
  },
];

export const mockSubjects: TSubject[] = [
  {
    id: 1,
    subjectCode: "CS101",
    subjectName: "Lập trình căn bản",
    credits: 3,
    description: "Môn học cơ bản về lập trình",
    major: mockMajors[0],
    createdAt: "2024-01-15T08:00:00Z",
  },
  {
    id: 2,
    subjectCode: "CS102",
    subjectName: "Cấu trúc dữ liệu và giải thuật",
    credits: 4,
    description: "Nghiên cứu các cấu trúc dữ liệu và thuật toán",
    major: mockMajors[1],
    createdAt: "2024-01-16T09:00:00Z",
  },
  {
    id: 3,
    subjectCode: "SE201",
    subjectName: "Công nghệ phần mềm",
    credits: 3,
    description: "Quy trình phát triển phần mềm",
    major: mockMajors[2],
    createdAt: "2024-01-17T10:00:00Z",
  },
  {
    id: 4,
    subjectCode: "DB301",
    subjectName: "Cơ sở dữ liệu",
    credits: 3,
    description: "Thiết kế và quản trị cơ sở dữ liệu",
    major: mockMajors[0],
    createdAt: "2024-01-18T11:00:00Z",
  },
  {
    id: 5,
    subjectCode: "SEC401",
    subjectName: "An toàn mạng",
    credits: 4,
    description: "Bảo mật hệ thống và mạng máy tính",
    major: mockMajors[3],
    createdAt: "2024-01-19T12:00:00Z",
  },
  {
    id: 6,
    subjectCode: "WEB201",
    subjectName: "Phát triển ứng dụng web",
    credits: 3,
    description: "Xây dựng ứng dụng web hiện đại",
    major: mockMajors[0],
    createdAt: "2024-01-20T13:00:00Z",
  },
  {
    id: 7,
    subjectCode: "AI301",
    subjectName: "Trí tuệ nhân tạo",
    credits: 4,
    description: "Cơ sở về AI và machine learning",
    major: mockMajors[1],
    createdAt: "2024-01-21T14:00:00Z",
  },
  {
    id: 8,
    subjectCode: "NET401",
    subjectName: "Mạng máy tính",
    credits: 3,
    description: "Kiến trúc và giao thức mạng",
    major: mockMajors[0],
    createdAt: "2024-01-22T15:00:00Z",
  },
  {
    id: 9,
    subjectCode: "ML501",
    subjectName: "Học máy nâng cao",
    credits: 4,
    description: "Các thuật toán machine learning phức tạp",
    major: mockMajors[1],
    createdAt: "2024-01-23T16:00:00Z",
  },
  {
    id: 10,
    subjectCode: "PROJ301",
    subjectName: "Quản lý dự án",
    credits: 2,
    description: "Kỹ năng quản lý dự án IT",
    major: mockMajors[2],
    createdAt: "2024-01-24T17:00:00Z",
  },
  {
    id: 11,
    subjectCode: "CRYPTO401",
    subjectName: "Mật mã học",
    credits: 3,
    description: "Lý thuyết và ứng dụng mật mã",
    major: mockMajors[3],
    createdAt: "2024-01-25T18:00:00Z",
  },
  {
    id: 12,
    subjectCode: "MOBILE301",
    subjectName: "Phát triển ứng dụng di động",
    credits: 3,
    description: "Xây dựng app cho iOS và Android",
    major: mockMajors[0],
    createdAt: "2024-01-26T19:00:00Z",
  },
];
